# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioPlayer', '0002_auto_20170713_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=10)),
                ('streamUrl', models.CharField(max_length=100)),
            ],
        ),
    ]
