# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audioPlayer', '0003_livestream'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioFile',
        ),
        migrations.DeleteModel(
            name='LiveStream',
        ),
    ]
