# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audioPlayer', '0004_auto_20170713_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_Url', models.CharField(max_length=100)),
                ('audio_File', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audioPlayer.AudioFile')),
            ],
        ),
    ]
