# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioPlayer', '0005_audiofile_livestream'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='time',
            field=models.TimeField(default='19:00'),
        ),
    ]
