# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioPlayer', '0006_livestream_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=50)),
                ('profile_image', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='livestream',
            name='audio_File',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='time',
            field=models.TimeField(default='19:00'),
        ),
        migrations.DeleteModel(
            name='LiveStream',
        ),
    ]
