# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audioPlayer', '0007_auto_20170718_2037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
